version: '3'
volumes:
   data:
networks:
  mariadbnet:
  redisnet:
services:
  schary-mono-backend:
    image: schary-mono-backend
    container_name: schary-mono
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mariadb
    networks:
      - redisnet
      - mariadbnet
    ports:
      - "30000:30000"
  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Lubricate-Macaroni7-Remember
      MYSQL_DATABASE: schary
      MYSQL_USER: Richly7724
      MYSQL_PASSWORD: Visor-Unearth-Atrocious5
    volumes:
      - data:/var/lib/mysql
    networks:
      - mariadbnet
    ports:
      - "3306:3306"
  redis:
    image: redis:7-bullseye
    restart: always
    networks:
      - redisnet
    ports:
      - '6379:6379'
