version: '3'
volumes:
   data:
services:
  schary-mono-backend:
    image: schary-mono-backend
    container_name: schary-mono
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "30000:30000"
  maridb:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Lubricate-Macaroni7-Remember
      MYSQL_DATABASE: schary
      MYSQL_USER: Richly7724
      MYSQL_PASSWORD: Visor-Unearth-Atrocious5
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:7-bullseye
