//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::class::Entity as Class;
pub use super::permision::Entity as Permision;
pub use super::user::Entity as User;
pub use super::user_permision::Entity as UserPermision;
