//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_permision")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i32,
    pub permision_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::permision::Entity",
        from = "Column::PermisionId",
        to = "super::permision::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Permision,
    #[sea_orm(has_many = "super::user::Entity")]
    User,
}

impl Related<super::permision::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Permision.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
